
(function(){
  'use strict';
  const $=(id)=>document.getElementById(id);
  function token(){ return localStorage.getItem('pope_token')||sessionStorage.getItem('pope_token')||localStorage.getItem('pope_session_token')||sessionStorage.getItem('pope_session_token')||''; }
  async function api(path,opt={}){ const base=(window.__POPE_API_BASE__||localStorage.getItem('pope_api_base')||'https://popeonline-staging.onrender.com').replace(/\/$/,''); const headers={'Content-Type':'application/json'}; const t=token(); if(t)headers.Authorization='Bearer '+t; const r=await fetch(base+path,{method:opt.method||'GET',headers,body:opt.body?JSON.stringify(opt.body):undefined,credentials:'include'}); let d=null; try{d=await r.json()}catch(e){} if(!r.ok){ const err=new Error((d&&(d.detail||d.message||d.error))||('HTTP '+r.status)); err.data=d; throw err;} return d; }
  function currentUser(){ if(window.selectedUser) return window.selectedUser; const id=window.__selectedUserId || document.body.dataset.selectedUserId || sessionStorage.getItem('pope_admin_selected_user_id'); if(id) return {id}; const title=$('ficheTitleBar')?.textContent||''; return null; }
  function val(id){return ($(id)||{}).value||''}
  function payload(){ const domaines=Array.from(document.querySelectorAll('.fiche-domaine:checked')).map(x=>x.value); return {nom:val('ficheNom'),categorie:val('ficheCategorie'),territoire:val('ficheTerritoire'),size:val('ficheSize'),contact:val('ficheContact'),contact_email:val('ficheContactEmail'),contact_phone:val('ficheContactPhone'),contact_direct:val('ficheContactDirect'),niveau:val('ficheNiveau'),source:val('ficheSource'),domaines,besoins:val('ficheBesoins'),mode:val('ficheMode'),urgence:val('ficheUrgence'),stade:val('ficheStade'),maturite:val('val-maturite'),complexite:val('val-complexite'),potentiel:val('val-potentiel'),fidelite:val('val-fidelite'),decision:val('ficheDecision'),responsable:val('ficheResponsable'),responsable_expert_id:val('ficheResponsableExpertId'),notes:val('ficheNotes'),budget:val('ficheBudget'),financement:val('ficheFinancement'),duree:val('ficheDuree'),crm_statut:val('ficheCrmStatut'),prochain_contact:val('ficheProchainContact'),canal_pref:val('ficheCanalPref'),actions:val('ficheActions'),echeance:val('ficheEcheance'),livrable:val('ficheLivrable'),sensibilite:val('ficheSensibilite'),public_concerne:val('fichePublic'),decision_attendue:val('ficheDecisionAttendue')}; }
  function msg(txt,ok){const m=$('ficheMsg'); if(m){m.textContent=txt;m.className='adm-msg '+(ok?'adm-msg-ok':'adm-msg-err');m.style.display='block';}}
  window.saveFicheClient=async function(){ const u=currentUser(); if(!u||!u.id){msg('❌ Aucun client sélectionné : ouvrez une fiche client depuis la liste.',false);return;} try{ const res=await api('/admin/client-fiche/'+encodeURIComponent(u.id),{method:'POST',body:payload()}); localStorage.setItem('pope_fiche_'+u.id,JSON.stringify({...payload(),...res})); msg('✅ Fiche enregistrée en base — '+new Date(res.saved_at||Date.now()).toLocaleString('fr-FR'),true); if(window.showToast)window.showToast('Fiche enregistrée en BDD','ok'); }catch(e){ msg('❌ Échec sauvegarde BDD : '+(e.data?.detail||e.message||e),false); if(window.showToast)window.showToast('Échec sauvegarde fiche','err'); } };
  const oldOpen=window.openPanel; if(typeof oldOpen==='function'){ window.openPanel=function(id){ window.__selectedUserId=id; sessionStorage.setItem('pope_admin_selected_user_id',id); return oldOpen.apply(this,arguments);}; }
})();
