CREATE TABLE IF NOT EXISTS client_fiches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  nom TEXT,
  categorie TEXT,
  territoire TEXT,
  taille TEXT,
  contact TEXT,
  contact_direct TEXT,
  niveau_decisionnel TEXT,
  source TEXT,
  domaines TEXT[] DEFAULT '{}',
  description_besoin TEXT,
  mode_intervention TEXT,
  urgence TEXT,
  stade TEXT,
  maturite INTEGER CHECK (maturite BETWEEN 1 AND 5),
  complexite INTEGER CHECK (complexite BETWEEN 1 AND 5),
  potentiel INTEGER CHECK (potentiel BETWEEN 1 AND 5),
  fidelite INTEGER CHECK (fidelite BETWEEN 1 AND 5),
  decision TEXT,
  responsable TEXT,
  notes TEXT,
  budget TEXT,
  financement TEXT,
  duree TEXT,
  crm_statut TEXT,
  prochain_contact DATE,
  canal_pref TEXT,
  actions TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_client_fiches_user_id ON client_fiches(user_id);
